export const MOCK_ADDRESSES = [
  {
    id: 1,
    label: "Ev",
    name: "Ayşe Yılmaz",
    phone: "(530) *** ** 12",
    line1: "Atatürk Mah. Gül Sok. No:5 Daire:3",
    line2: "06000 - Ankara / Etimesgut",
    isCorporate: false,
  },
  {
    id: 2,
    label: "İş",
    name: "Ayşe Yılmaz",
    phone: "(535) *** ** 95",
    line1: "Kızılay Cad. No:12 Kat:3",
    line2: "06420 - Ankara / Çankaya",
    isCorporate: false,
  },
  {
    id: 3,
    label: "Annem",
    name: "Fatma Kaya",
    phone: "(530) *** ** 12",
    line1: "Bahçelievler Mah. Lale Sok. No:8",
    line2: "06490 - Ankara / Yenimahalle",
    isCorporate: false,
  },
  {
    id: 4,
    label: "Ayesoft",
    name: "Ayesoft A.Ş.",
    phone: "(530) *** ** 12",
    line1: "OSB 2. Cadde No:42",
    line2: "06370 - Ankara / Ostim",
    isCorporate: true,
  },
  {
    id: 5,
    label: "Ayesoft",
    name: "Ayesoft A.Ş.",
    phone: "(530) *** ** 12",
    line1: "OSB 2. Cadde No:42",
    line2: "06370 - Ankara / Ostim",
    isCorporate: true,
  },
  {
    id: 6,
    label: "Ayesoft",
    name: "Ayesoft A.Ş.",
    phone: "(530) *** ** 12",
    line1: "OSB 2. Cadde No:42",
    line2: "06370 - Ankara / Ostim",
    isCorporate: true,
  },
  {
    id: 7,
    label: "Ayesoft",
    name: "Ayesoft A.Ş.",
    phone: "(530) *** ** 12",
    line1: "OSB 2. Cadde No:42",
    line2: "06370 - Ankara / Ostim",
    isCorporate: true,
  },
];

export const EMPTY_FORM = {
  label: "",
  name: "",
  phone: "",
  line1: "",
  line2: "",
  isCorporate: false,
};